/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCollectionRouteImport } from './routes/admin/collection'
import { Route as ApiVideoUuidRouteImport } from './routes/api/video/$uuid'
import { Route as ApiAdminThumbFileidRouteImport } from './routes/api/admin/thumb/$fileid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionRoute = AdminCollectionRouteImport.update({
  id: '/admin/collection',
  path: '/admin/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoUuidRoute = ApiVideoUuidRouteImport.update({
  id: '/api/video/$uuid',
  path: '/api/video/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminThumbFileidRoute = ApiAdminThumbFileidRouteImport.update({
  id: '/api/admin/thumb/$fileid',
  path: '/api/admin/thumb/$fileid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/collection': typeof AdminCollectionRoute
  '/api/video/$uuid': typeof ApiVideoUuidRoute
  '/api/admin/thumb/$fileid': typeof ApiAdminThumbFileidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/collection': typeof AdminCollectionRoute
  '/api/video/$uuid': typeof ApiVideoUuidRoute
  '/api/admin/thumb/$fileid': typeof ApiAdminThumbFileidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/collection': typeof AdminCollectionRoute
  '/api/video/$uuid': typeof ApiVideoUuidRoute
  '/api/admin/thumb/$fileid': typeof ApiAdminThumbFileidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/collection'
    | '/api/video/$uuid'
    | '/api/admin/thumb/$fileid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/collection'
    | '/api/video/$uuid'
    | '/api/admin/thumb/$fileid'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/collection'
    | '/api/video/$uuid'
    | '/api/admin/thumb/$fileid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCollectionRoute: typeof AdminCollectionRoute
  ApiVideoUuidRoute: typeof ApiVideoUuidRoute
  ApiAdminThumbFileidRoute: typeof ApiAdminThumbFileidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection': {
      id: '/admin/collection'
      path: '/admin/collection'
      fullPath: '/admin/collection'
      preLoaderRoute: typeof AdminCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/$uuid': {
      id: '/api/video/$uuid'
      path: '/api/video/$uuid'
      fullPath: '/api/video/$uuid'
      preLoaderRoute: typeof ApiVideoUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/thumb/$fileid': {
      id: '/api/admin/thumb/$fileid'
      path: '/api/admin/thumb/$fileid'
      fullPath: '/api/admin/thumb/$fileid'
      preLoaderRoute: typeof ApiAdminThumbFileidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCollectionRoute: AdminCollectionRoute,
  ApiVideoUuidRoute: ApiVideoUuidRoute,
  ApiAdminThumbFileidRoute: ApiAdminThumbFileidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
